### ISSUE TITLE
SimpleWebAuthn Cookbooks

### ISSUE THREAD

**Issue by JayHelton** [MasterKale/SimpleWebAuthn-homepage#2]
The SimpleWebAuthn node packages are both in really great state. 
The biggest room for improvement within SimpleWebAuthn would probably be the documentation.

The documentation is good, but currently WebAuthn details and information is pretty hard to come by and sometimes even harder to fully comprehend without diving into the complicated specifications.

@MasterKale had the idea to create SimpleWebAuthn cookbooks that would provide well documented source code for different use cases of WebAuthn using the SimpleWebauthn libraries. The goal would be to cover specific scenarios that a developer might come across and have a resource that can be _mostly_ copy and pasted. 

We shouldn't worry too much about the scenarios being very similar looking. The WebAuthn protocol is well abstracted so most scenarios will have a pretty small diff.

We should also be sure to comment and highlight specific details that matter within the context of the scenario (i.e. pointing out the differences in user verification for some scenario).

Lastly, we should be sure to include documentation and specification citations to allow developers quick access to important details. Personally, I fall on the side of over documenting which can be dangerous if the spec details change without noticing. On the flip side, I think there are some obscure details in WebAuthn that are difficult to fully comprehend, and it would be good to try and clarify that. Example being https://www.w3.org/TR/webauthn-2/#sctn-credential-storage-modality. This particular part of the spec flew over my head quite a few times!

Here are some websites for a little inspiration:

Content:
- https://www.passwordless.dev/

Cookbook Examples:
- https://rust-lang-nursery.github.io/rust-cookbook/
- https://docs.nestjs.com/recipes

Here are a few ideas for the cookbook recipes:
- WebAuthn as a second factor
- Usernameless with WebAuthn
- Passwordless with WebAuthn
- Device Certificate Attestation
- Requiring Security Key Pin Code
- User Initiated Events for IOS/Big Sur support

**Comment by MasterKale** [comment]
Thank you for opening this up, it nicely summarizes some additional documentation I've been wanting to add to the site.

I realized after our conversation that the "cookbook" idea could include a checklist of sorts for RP developers to go down. In addition to specific options they could pass into SimpleWebAuthn, the checklist could highlight steps like "persist `options.challenge` in a way that associates it to the current user before returning options", "store the value of `verification.assertionInfo.newCounter` after assertion verification", things like that.

**Comment by JayHelton** [comment]
Definitely! I like the checklist idea. There are a handful of important, but small details that should be pointed out.

What ive start working on is for the 3 large scenarios (2FA, passwordless, usernameless) to be a bit more in depth and, almost tutorial like. Here is an example of my writing style for more full scale tutorials: https://fireship.io/lessons/game-lobby-with-firebase-reactfire.

If you are cool with that type of content, ill keep writing them and send you the drafts.

Then I was thinking there could be some more targeted recipes around user verification, only allow roaming or platform, instead of both, etc. Somethings that dont quite need a full tutorial style page if youve worked through the larger samples.

**Comment by MasterKale** [comment]
> If you are cool with that type of content, ill keep writing them and send you the drafts.

I like it, I like it 🚀 

> Then I was thinking there could be some more targeted recipes around user verification, only allow roaming or platform, instead of both, etc. Somethings that dont quite need a full tutorial style page if youve worked through the larger samples.

This sounds good too. "Mixins" or whatever (don't feel constrained to these terms if something better pops up) that could be used to tweak the baseline cookbook recipe...

**Comment by JayHelton** [comment]
I'm shooting for a full 1st draft completion around early march (doing most of my writing on the weekends), then once the draft is reviewed, ill start the draft pull request to integrate the markdown draft into the website!

**Comment by MasterKale** [comment]
I think it's time to close this out, the library's tuned to default to passwordless use of WebAuthn, and there's now a passkeys section in the docs for those RP's who want to take things to the next usernameless level:

https://simplewebauthn.dev/docs/advanced/passkeys

This and https://passkeys.dev/ should be sufficient direction in 2023 for RP's to get started using WebAuthn and passkeys.
