### ISSUE TITLE
Link is broken for UMD script tag in docs

### ISSUE THREAD

**Issue by forevermatt** [MasterKale/SimpleWebAuthn-homepage#6]
The example in the [SimpleWebAuthn browser docs](https://simplewebauthn.dev/docs/packages/browser#umd) for including `@simplewebauthn/browser` using a normal script tag seems to have a broken link.

It says to use this:
```html
<script src="https://unpkg.com/@simplewebauthn/browser/dist/simplewebauthn-browser.min.js"></script>
```

However, that returns a 404. Is it supposed to be this?
```html
<script src="https://unpkg.com/@simplewebauthn/browser@4.1.0/dist/bundle/index.umd.min.js"></script>
```

I'll be glad to submit a PR if so. Thanks!

---

P.S. If you are okay with it, I'll actually submit the PR as this, to protect against malware injection by using the subresource integrity feature:
```html
<script src="https://unpkg.com/@simplewebauthn/browser@4.1.0/dist/bundle/index.umd.min.js" integrity="sha384-WiaH30NJIrU5UVPRVBjvWA8J1olK/4OMlboN6o6NTmQW7XExLsqc6OFbKvhFoPAj" crossorigin="anonymous"></script>
```

**Comment by MasterKale** [comment]
Hello @forevermatt, thank you for calling this out. You're correct that the link should be the following instead:

```
https://unpkg.com/@simplewebauthn/browser/dist/bundle/index.umd.min.js
```

I really like your suggestion to use `integrity` and `crossorigin`, but I fear it would quickly fall out of date as I release new versions and then run out of time/forget to double back to docs and update these values. If you're feeling like contributing, might you have a way to automate updating that specific section of the Browser docs to update the URL and integrity checksum during a build? I just checked, if you `HEAD https://unpkg.com/@simplewebauthn/browser/dist/bundle/index.umd.min.js` you get back a 302 to the actual versioned URL:

```$> curl --HEAD https://unpkg.com/@simplewebauthn/browser/dist/bundle/index.umd.min.js
HTTP/2 302
date: Thu, 25 Nov 2021 03:41:14 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
cache-control: public, s-maxage=600, max-age=60
location: /@simplewebauthn/browser@4.1.0/dist/bundle/index.umd.min.js
vary: Accept
via: 1.1 fly.io
fly-request-id: 01FNAJKAAAX80KSYTWMCZMFZ5W
cf-cache-status: HIT
age: 341
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 6b37dc38981a7d07-LAX
```

Maybe there's some way to programmatically do this during a build to get the actual URL, _somehow_ generate a checksum, then inject both into that specific section of the docs 🤔

**Comment by forevermatt** [comment]
Hmm, yes. Adding the maintenance burden of having to update that hash on every release isn't ideal.

Well, for the moment I'll submit a PR to at least fix the URL. Sadly, I don't have time to build an elegant solution for adding the integrity checksum. Ahh, well... so many interesting challenges, so little time. 🙂
